export const BOOKMARK_FOLDERS_REQUEST_STARTED = 'BOOKMARK_FOLDERS_REQUEST_STARTED';
export const BOOKMARK_FOLDERS_REQUEST_FINISHED = 'BOOKMARK_FOLDERS_REQUEST_FINISHED';

export const BOOKMARK_FOLDERS_IDS_SELECTED = 'BOOKMARK_FOLDERS_IDS_SELECTED';
export const BOOKMARK_FOLDERS_IDS_DESELECTED = 'BOOKMARK_FOLDERS_IDS_DESELECTED';
